version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/service
    image: ewm-stats-service
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  ewm-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm_main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm-main-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_main_db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root