version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/service
    image: ewm-stats-service
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:6541/ewm_stats_db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    command: -p 6541


  ewm-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm_main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:6542/ewm_main_db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_main_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    command: -p 6542